rclonebrowser_service:
    image: romancin/rclonebrowser:develop3
    container_name: rclonebrowser-develop
    ports:
      - "5804:5800"
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=Europe/Madrid
      - VNC_PASSWORD=password
    volumes:
      - "/share/Container/rclonebrowser-develop:/config:rw"
      - "/share/Container/rclonebrowser-develop/shared:/shared:rw"
